apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/selfsignedIssuer.yaml
  - resources/selfsignedRootCaCertificate.yaml
  - resources/huntInternalClusterIssuer.yaml
